apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: app1
        url: https://kubernetes.default.svc
      - cluster: app2
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/Rwatana/k8s-practice.git
        targetRevision: HEAD
        path: app
      destination:
        server: '{{url}}'
        namespace: default