name: Build and Push Docker Images to ECR Repositories

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t $ECR_REGISTRY/app-repo:$IMAGE_TAG -f ./build/app/Dockerfile.prod .
          docker build -t $ECR_REGISTRY/web-repo:$IMAGE_TAG -f ./build/web/Dockerfile .
          docker build -t $ECR_REGISTRY/migration-repo:$IMAGE_TAG -f ./build/migration/Dockerfile .
          docker push $ECR_REGISTRY/app-repo:$IMAGE_TAG
          docker push $ECR_REGISTRY/web-repo:$IMAGE_TAG
          docker push $ECR_REGISTRY/migration-repo:$IMAGE_TAG

      - name: Checkout config repository
        uses: actions/checkout@v2
        with:
          repository: Rwatana/k8s-practice
          ref: ${{ github.ref }}
          token: ${{ secrets.PAT }}
          path: 'k8s-practice'  # Ensure this is the correct path to your Kubernetes configuration repository

      - name: Update image tag
        id: update-image-tag
        working-directory: ./k8s-practice
        continue-on-error: true
        run: |
          yq e -i '.front.imageTag = env(IMAGE_TAG)' ./main/values.yaml
          git diff --name-only --exit-code || echo "No changes to commit."

      - name: Commit and push
        if: steps.update-image-tag.outcome != 'success'
        working-directory: ./k8s-practice
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update image tag to $IMAGE_TAG"
          git push
